print("circle")
r=int(input("enter radious"))
print(3.14*r*r)
print("rectangle")
l=int(input("enter  length"))
b=int(input("enter  breadth"))
print(l*b)
print("triangle")
b=int(input("enter  base"))
h=int(input("enter  height "))
print(0.5*b*h)
